/* eslint-disable */
// Generated by Wrangler by running `wrangler types worker-configuration.d.ts --include-runtime=false` (hash: 1bbee9f64083165e0695950fb2896f9e)
declare namespace Cloudflare {
	interface Env {
		AI: Ai;
		DATABASE_URL: string;
		E2E_TEST_MODE: string;
		BETTER_AUTH_URL: string;
		FRONTEND_URL: string;
		GOOGLE_CLIENT_ID: string;
		GOOGLE_CLIENT_SECRET: string;
		JWT_SECRET: string;
		GOOGLE_REDIRECT_URI: string;
		APP_URL: string;
		BETTER_AUTH_SECRET: string;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DATABASE_URL" | "E2E_TEST_MODE" | "BETTER_AUTH_URL" | "FRONTEND_URL" | "GOOGLE_CLIENT_ID" | "GOOGLE_CLIENT_SECRET" | "JWT_SECRET" | "GOOGLE_REDIRECT_URI" | "APP_URL" | "BETTER_AUTH_SECRET">> {}
}
