import { expect, test } from '@playwright/test'
import { failAppProcedure, openAppAsAnonymous, setServerNowFromBrowserClock } from './helpers/auth'

test('Reviewを直接開いて年間カレンダーをdesktop・mobileで表示する', async ({ page }) => {
  const fixedNow = new Date('2026-10-06T12:00:00.000Z')
  await page.clock.install({ time: fixedNow })
  await page.addInitScript((value) => localStorage.setItem('pomdo-e2e-now', value), fixedNow.toISOString())
  await page.goto('/app/review')
  await setServerNowFromBrowserClock(page)
  await expect(page.getByRole('heading', { name: '年間の集中時間' })).toBeVisible()
  await expect(page.getByText('合計集中時間')).toBeVisible()
  const calendar = page.getByRole('group', { name: /\d{4}年の集中時間/ })
  await expect(calendar).toBeVisible()
  await expect(page.getByText('直近7日')).toHaveCount(0)
  await expect(page.getByRole('img', { name: '直近7日の集中時間' })).toHaveCount(0)
  await expect(page.locator('.annual-calendar-month')).toHaveCount(12)
  const calendarYear = Number((await page.locator('.annual-calendar-heading strong').innerText()).replace('年', ''))
  const expectedDays = new Date(Date.UTC(calendarYear, 1, 29)).getUTCDate() === 29 ? 366 : 365
  const dayDates = await calendar.locator('.annual-calendar-day').evaluateAll((cells) => cells.map((cell) => (cell as HTMLElement).dataset.date))
  expect(dayDates).toHaveLength(expectedDays)
  expect(new Set(dayDates).size).toBe(expectedDays)

  const weeklyLayout = page.locator('.annual-calendar-week-layout')
  await expect.poll(() => weeklyLayout.evaluate((element) => getComputedStyle(element).display)).toBe('grid')
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  const assertTooltipFitsViewport = async (day: ReturnType<typeof calendar.locator>) => {
    await day.hover()
    const tooltipBox = await page.getByRole('tooltip').boundingBox()
    const viewport = page.viewportSize()
    expect(tooltipBox).not.toBeNull()
    expect(viewport).not.toBeNull()
    expect(tooltipBox!.x).toBeGreaterThanOrEqual(0)
    expect(tooltipBox!.y).toBeGreaterThanOrEqual(0)
    expect(tooltipBox!.x + tooltipBox!.width).toBeLessThanOrEqual(viewport!.width)
    expect(tooltipBox!.y + tooltipBox!.height).toBeLessThanOrEqual(viewport!.height)
  }
  await assertTooltipFitsViewport(calendar.locator('.annual-calendar-day').first())
  await assertTooltipFitsViewport(calendar.locator('.annual-calendar-day').last())

  await page.setViewportSize({ width: 768, height: 900 })
  await expect.poll(() => weeklyLayout.evaluate((element) => getComputedStyle(element).display)).toBe('grid')
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  const today = calendar.locator('[aria-current="date"]')
  const todayDate = await today.getAttribute('data-date')
  await today.focus()
  await page.keyboard.press('ArrowRight')
  const desktopTargetDate = new Date(`${todayDate}T00:00:00.000Z`)
  desktopTargetDate.setUTCDate(desktopTargetDate.getUTCDate() + 7)
  const desktopTarget = calendar.locator(`[data-date="${desktopTargetDate.toISOString().slice(0, 10)}"]`)
  await expect(desktopTarget).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(desktopTarget).not.toBeFocused()
  await expect(page.getByRole('tooltip')).toHaveCount(0)

  await page.setViewportSize({ width: 390, height: 844 })
  await expect.poll(() => weeklyLayout.evaluate((element) => getComputedStyle(element).display)).toBe('block')
  const monthGrid = page.locator('.annual-calendar-month-days').first()
  const mobileColumns = await monthGrid.evaluate((element) => getComputedStyle(element).gridTemplateColumns.split(' ').length)
  expect(mobileColumns).toBe(7)
  for (const month of await page.locator('.annual-calendar-month').all()) {
    const monthDays = month.locator('.annual-calendar-day')
    await assertTooltipFitsViewport(monthDays.first())
    await assertTooltipFitsViewport(monthDays.last())
  }
  await today.focus()
  await page.keyboard.press('ArrowRight')
  const mobileTargetDate = new Date(`${todayDate}T00:00:00.000Z`)
  mobileTargetDate.setUTCDate(mobileTargetDate.getUTCDate() + 1)
  const mobileTarget = calendar.locator(`[data-date="${mobileTargetDate.toISOString().slice(0, 10)}"]`)
  await expect(mobileTarget).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(mobileTarget).not.toBeFocused()
  await expect(page.getByRole('tooltip')).toHaveCount(0)
  await today.focus()
  const buttonTopBeforeScroll = await today.evaluate((element) => element.getBoundingClientRect().top)
  await page.mouse.wheel(0, 120)
  await expect.poll(() => today.evaluate((element) => element.getBoundingClientRect().top)).not.toBe(buttonTopBeforeScroll)
  const tooltipGeometry = await page.evaluate(() => {
    const button = document.querySelector<HTMLElement>('.annual-calendar-day[aria-current="date"]')
    const tooltip = document.querySelector<HTMLElement>('.annual-calendar-tooltip')
    if (!button || !tooltip) return null
    const buttonRect = button.getBoundingClientRect()
    const tooltipRect = tooltip.getBoundingClientRect()
    return {
      aboveGap: buttonRect.top - tooltipRect.bottom,
      belowGap: tooltipRect.top - buttonRect.bottom,
      inViewport: tooltipRect.top >= 0 && tooltipRect.bottom <= innerHeight,
    }
  })
  expect(tooltipGeometry).not.toBeNull()
  expect(tooltipGeometry!.inViewport).toBe(true)
  expect(Math.min(Math.abs(tooltipGeometry!.aboveGap - 8), Math.abs(tooltipGeometry!.belowGap - 8))).toBeLessThan(2)
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})

test('ReviewとSettingsから記録を確認し、アカウントを削除してLPへ戻れる', async ({ page }) => {
  test.setTimeout(60_000)
  const fixedNow = new Date('2026-10-06T12:00:00.000Z')
  await page.clock.install({ time: fixedNow })
  await page.addInitScript((value) => localStorage.setItem('pomdo-e2e-now', value), fixedNow.toISOString())
  await openAppAsAnonymous(page)
  await setServerNowFromBrowserClock(page)
  await page.getByRole('button', { name: '15' }).click()
  await page.getByRole('button', { name: '▶ はじめる' }).click()
  await page.clock.runFor('00:15:01')
  await expect(page.getByText('ひと区切り。少し休みますか？')).toBeVisible()
  await page.getByRole('button', { name: 'もう1本' }).click()

  await page.getByRole('link', { name: /振り返りを見る/ }).click()
  await expect(page).toHaveURL(/\/app\/review$/)
  await expect(page.getByRole('heading', { name: '年間の集中時間' })).toBeVisible()
  await expect(page.getByRole('group', { name: '2026年の集中時間' })).toBeVisible()
  const recordedDay = page.getByRole('button', { name: /^2026年10月6日、.*集中時間 15分$/ })
  await expect(recordedDay).toBeVisible()
  await recordedDay.hover()
  await expect(page.getByRole('tooltip')).toContainText('2026年10月6日（火）')
  await expect(page.getByRole('tooltip')).toContainText('集中時間 15分')
  const pastZeroDay = page.getByRole('button', { name: '2026年10月5日、月曜日、集中時間 0分' })
  await pastZeroDay.hover()
  await expect(page.getByRole('tooltip')).toContainText('2026年10月5日（月）')
  await expect(page.getByRole('tooltip')).toContainText('集中時間 0分')
  const futureDay = page.getByRole('button', { name: '2026年10月7日、水曜日、集中時間 0分' })
  await futureDay.hover()
  const tooltip = page.getByRole('tooltip')
  await expect(tooltip).toContainText('2026年10月7日（水）')
  await expect(tooltip).toContainText('集中時間 0分')
  const tooltipBox = await tooltip.boundingBox()
  expect(tooltipBox).not.toBeNull()
  await page.mouse.move(tooltipBox!.x + tooltipBox!.width / 2, tooltipBox!.y + tooltipBox!.height / 2)
  await expect(tooltip).toBeVisible()
  await page.getByRole('heading', { name: '年間の集中時間' }).hover()
  await expect(tooltip).toHaveCount(0)
  await expect(page.getByText('直近7日')).toHaveCount(0)
  await expect(page.getByText(/累計 \d+日/)).toBeVisible()

  await page.setViewportSize({ width: 390, height: 844 })
  await expect.poll(() => page.locator('.annual-calendar-week-layout').evaluate((element) => getComputedStyle(element).display)).toBe('block')
  await recordedDay.focus()
  await expect(page.getByRole('tooltip')).toContainText('集中時間 15分')
  await page.keyboard.press('Space')
  await expect(page.locator('.annual-calendar-selection')).toHaveCount(0)
  await expect(recordedDay).not.toHaveAttribute('aria-pressed')
  await page.keyboard.press('ArrowRight')
  await expect(page.getByRole('button', { name: '2026年10月7日、水曜日、集中時間 0分' })).toBeFocused()
  await expect(page.getByRole('tooltip')).toContainText('2026年10月7日（水）')
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)

  await page.getByRole('link', { name: 'アプリへ戻る' }).click()
  await page.getByRole('link', { name: '設定' }).click()
  await page.getByRole('button', { name: 'JSONをエクスポート' }).click()
  await expect(page.getByRole('heading', { name: '設定' })).toBeVisible()
  const deleteResponsePromise = page.waitForResponse(
    (response) => response.url().includes('/api/trpc/account.delete') && response.request().method() === 'POST',
    { timeout: 15_000 },
  )
  page.once('dialog', (dialog) => void dialog.accept())
  await page.getByRole('button', { name: 'アカウントを削除' }).click()
  const deleteResponse = await deleteResponsePromise
  expect(deleteResponse.status()).toBe(200)
  await expect(page).toHaveURL(/\/$/, { timeout: 15_000 })
  await expect(page.getByRole('link', { name: '使ってみる' })).toBeVisible()
})

test('Reviewの日付情報をtouch tapで開閉し、別日へ切り替えられる', async ({ browser }) => {
  const fixedNow = new Date('2026-10-06T12:00:00.000Z')
  const context = await browser.newContext({
    baseURL: process.env.BASE_URL || 'http://localhost:5173',
    hasTouch: true,
    viewport: { width: 390, height: 844 },
  })
  const page = await context.newPage()
  await page.clock.install({ time: fixedNow })
  await page.addInitScript((value) => localStorage.setItem('pomdo-e2e-now', value), fixedNow.toISOString())
  await page.goto('/app/review')
  await setServerNowFromBrowserClock(page)
  await expect(page.getByRole('group', { name: '2026年の集中時間' })).toBeVisible()
  const dateMutationRequests: string[] = []
  page.on('request', (request) => {
    if (request.url().includes('/api/trpc/') && request.method() === 'POST') dateMutationRequests.push(request.url())
  })

  const firstDay = page.getByRole('button', { name: '2026年10月7日、水曜日、集中時間 0分' })
  const secondDay = page.getByRole('button', { name: '2026年10月8日、木曜日、集中時間 0分' })
  await firstDay.tap()
  await expect(page.getByRole('tooltip')).toContainText('2026年10月7日（水）')
  await firstDay.tap()
  await expect(page.getByRole('tooltip')).toHaveCount(0)
  await firstDay.tap()
  await expect(page.getByRole('tooltip')).toContainText('2026年10月7日（水）')
  await secondDay.tap()
  await expect(page.getByRole('tooltip')).toContainText('2026年10月8日（木）')
  await page.getByRole('heading', { name: '10月' }).tap()
  await expect(page.getByRole('tooltip')).toHaveCount(0)
  await firstDay.tap()
  await expect(page.getByRole('tooltip')).toContainText('2026年10月7日（水）')
  await page.getByRole('heading', { name: '年間の集中時間' }).tap()
  await expect(page.getByRole('tooltip')).toHaveCount(0)
  await expect(firstDay).not.toHaveAttribute('aria-pressed')
  await expect(page.locator('.annual-calendar-selection')).toHaveCount(0)
  expect(dateMutationRequests).toEqual([])
  await context.close()
})

test('Review APIが失敗した場合は既存のエラー表示を保つ', async ({ page }) => {
  await failAppProcedure(page, 'review.summary')
  await page.goto('/app/review')
  await expect(page.getByText('振り返りを読み込めませんでした。')).toBeVisible({ timeout: 20_000 })
  await expect(page.getByRole('group', { name: /\d{4}年の集中時間/ })).toHaveCount(0)
})
